# Generated by Django 4.2.2 on 2023-10-31 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='ratings',
        ),
        migrations.AlterField(
            model_name='comments',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cccf427c-4a25-433b-a87e-1e5143cef4dc'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cccf427c-4a25-433b-a87e-1e5143cef4dc'), primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('cccf427c-4a25-433b-a87e-1e5143cef4dc'), primary_key=True, serialize=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.recipes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
